databases:
  - name: feedback_friday
    databaseName: feedback_friday
    user: feedback_friday

services:
  - type: web
    name: feedback_friday
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feedback_friday
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
